-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "plug" TEXT[] DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "imageGallery" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "grade" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "ram" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "model" SET DEFAULT ARRAY[]::TEXT[];
